GroovyGrubs:
  repo: "n/a"
  projects:
    groovy:
      url: "http://sfsuswe.com/~f12g06/"
      description: "Website for sharing food recipes"
OpenMRS:
  repo: "https://code.google.com/p/sp2013-csc668-868-group1/"
  projects:
    openmrs:
      url: "n/a"
      description: "OpenMRS project"
Slide Puzzle:
  repo: "https://code.google.com/p/su-13-project-slide-puzzle/"
  projects:
    puzzle:
      url: "n/a"
      description: "A slide puzzle game done in Unity"
Ruby on Rails:
  repo: "https://github.com/darthyoshi/csc867project"
  projects:
    site:
      url: "/"
      description: "This site"
    calendar:
      url: "/projects/calendar"
      description: "A basic interactive calendar (persistent)"
ArtSale:
  repo: "/https://github.com/darthyoshi/csc-667-867-team-yak"
  projects:
    artsale:
      url: "http://artsale.heroku.com"
      description: "Website for buying and selling artwork"
Untouchable:
  repo: "https://code.google.com/p/csc780-project-kchoi/"
  projects:
    android:
      url: "n/a"
      description: "An Android game"
Processing:
  repo: "https://github.com/darthyoshi/Processing"
  projects:
    processing:
      url: "n/a"
      description: "simple image browser"
Quickshow:
  repo: "https://github.com/darthyoshi/quickshow"
  projects:
    quickshow:
      url: "n/a"
      description: "Quickshow slide show player"
