"LAMP":
  "https://github.com/darthyoshi/groovygrubs":
    date: "Fall 2012"
    projects:
      GroovyGrubs:
        url: "/groovygrubs"
        description: "A website for sharing food recipes"
Java:
  "https://github.com/darthyoshi/sp2013-csc668-868-group1/tree/master/OpenMRSSubmissions":
    date: "Spring 2013"
    projects:
      "OpenMRS DSS Module":
        url: "/openmrs"
        description: "A module for OpenMRS"
  "https://github.com/darthyoshi/Processing":
    date: "Fall 2014"
    projects:
      ImageBrowser:
        url: "/imagebrowser"
        description: "A simple image browser"
  "https://github.com/darthyoshi/quickshow":
    date: "Fall 2014"
    projects:
      Quickshow:
        url: "/quickshow"
        description: "A slide show player"
Unity:
  "https://github.com/darthyoshi/su-13-project-slide-puzzle":
    date: "Summer 2013"
    projects:
      SlidePuzzle:
        url: "/slidepuzzle"
        description: "A slide puzzle game done in Unity"
Rails:
  "https://github.com/darthyoshi/csc867project":
    date: "Fall 2013"
    projects:
      "Portfolio":
        url: "/about#site"
        description: "This site"
      Calendar:
        url: "/calendar"
        description: "A basic interactive calendar"
  "https://github.com/darthyoshi/csc-667-867-team-yak":
    date: "Fall 2013"
    projects:
      ArtSale:
        url: "/artsale"
        description: "A website for buying and selling artwork"
Android:
  "https://github.com/darthyoshi/csc780-project-kchoi":
    date: "Spring 2014"
    projects:
      Untouchable:
        url: "/untouchable"
        description: "An Android game"
