project_0:
  url: "/projects/"
  description: "Environment Set Up"
project_1:
  url: "/projects/"
  description: "Custom Home Page Route"
project_2:
  url: "/projects/project_2"
  description: "Description of Bootstrap set up"
project_3:
  url: "/projects/calendar"
  description: "A basic interactive calendar (non-persistent) [deprecated]"
project_4:
  url: "/projects/calendar"
  description: "A basic interactive calendar (persistent)"
