Home:
  url: "/"
  title: "Home Page"
About:
  url: "/about"
  title: "About"
Resume:
  url: "/about/resume"
  title: "Resume"
Projects:
  url: "/projects"
  title: "A list of my projects"
Calendar:
  url: "/projects/calendar"
  title: "A basic interactive calendar"
