Home:
  url: "/"
  title: "Home Page"
About:
  url: "/about"
  title: "About"
ArtSale:
  url: "/artsale"
  title: "ArtSale"
BeeTracker:
  url: "/beetracker"
  title: "BeeTracker"
Calendar:
  url: "/calendar"
  title: "A basic interactive calendar"
GroovyGrubs:
  url: "/groovygrubs"
  title: "GroovyGrubs"
ImageBrowser:
  url: "/imagebrowser"
  title: "A simple image browser"
OpenMRS:
  url: "/openmrs"
  title: "OpenMRS DSS module"
Projects:
  url: "/projects"
  title: "Projects I've worked on"
Puzzle:
  url: "/slidepuzzle"
  title: "SlidePuzzle"
Quickshow:
  url: "/quickshow"
  title: "Quickshow"
Resume:
  url: "/about/resume"
  title: "Resume"
Untouchable:
  url: "/untouchable"
  title: "Untouchable"
Visualize:
  url: "/visualize"
  title: "Visualize"
YAJMinesweeper:
  url: "/yajminesweeper"
  title: "YAJMinesweeper"
