Home:
  url: "/"
  title: "Home Page"
About:
  url: "/about"
  title: "About"
Resume:
  url: "/about/resume"
  title: "Resume"
Projects:
  url: "/projects"
  title: "Projects I've worked on"
Calendar:
  url: "/calendar"
  title: "A basic interactive calendar"
Puzzle:
  url: "/slidepuzzle"
  title: "SlidePuzzle"
Untouchable:
  url: "/untouchable"
  title: "Untouchable"
ImageBrowser:
  url: "/imagebrowser"
  title: "A simple image browser"